services:
  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend.Dockerfile
    env_file:
      - deploy/.env.backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - moe-net

  frontend:
    build:
      context: .
      dockerfile: deploy/docker/frontend.Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_FLASK_API_URL: ${VITE_FLASK_API_URL}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3001:80"
    networks:
      - moe-net

networks:
  moe-net:
    driver: bridge
